### ISSUE TITLE
WARNING: DATA RACE

### ISSUE THREAD

**Issue by oseiberts11** [treydock/ssh_exporter#16]
Hi! We're building the exporter in our gitlab CI/CD and sometimes there is an error in the self-tests. 

There are some stack traces after a warning `WARNING: DATA RACE` after a connection failure `err="dial tcp: i/o timeout"`. I'm not sure which of these two is the root cause. I attach the full log file from the gitlab pipeline, so you can see all version numbers of everything. Hopefully it tells you something useful.

So far the issue is not very repeatable. It just happened twice so far and rerunning the job succeeded right away.

[logfile.txt](https://github.com/treydock/ssh_exporter/files/7312312/logfile.txt)

**Comment by oseiberts11** [comment]
I guess I would even change the `sleep` to something very long and the timeout to a few seconds. In that case, even very bad luck with scheduling, the connection time out is probably not going to happen, but waiting for the command to complete will time out. Which seems to be the point of the test.

**Comment by treydock** [comment]
Going to close but if this issue still happening let me know.  I haven't been seeing the race conditions lately so hopefully cleared up.
