### ISSUE TITLE
Unable to get the command output

### ISSUE THREAD

**Issue by KeerthigaKrishnan** [treydock/ssh_exporter#17]
Hi Team. 

I have configured ssh exporter to get remote command output. In case. of ssh_exporter /metrics I have all go metrics, /ssh i have below metrics 

++
# HELP ssh_duration_seconds How long the SSH check took in seconds
# TYPE ssh_duration_seconds gauge
ssh_duration_seconds 0.016062071
# HELP ssh_failure Indicates a failure
# TYPE ssh_failure gauge
ssh_failure{reason="command-error"} 0
ssh_failure{reason="command-output"} 0
ssh_failure{reason="error"} 1
ssh_failure{reason="timeout"} 0
# HELP ssh_success SSH connection was successful
# TYPE ssh_success gauge
ssh_success 0
++

This is my ssh_exporter.yaml file 

++
modules:
  default:
    user: prometheus
    password: secret
    command: uptime
    command_expect: "load average"
    timeout: 5
  key:
    user: prometheus
    private_key: /home/prometheus/.ssh/id_rsa
  verify:
    user: prometheus
    private_key: /home/prometheus/.ssh/id_rsa
    password: secret
    command: uptime
    command_expect: "load average"
    timeout: 5
++

Here uptime command metrics where we will get?. 

Is there any. sample grafana dashboard json for this. it will be helpful for me to. build with reference. 

Main use case. :  I have script which is running in cron job, I want to get the metrics of the script is running in cron. 

How can we achieved. Please share grafana dashboard and command output where we will get the metrics

**Comment by treydock** [comment]
The output is opt-in, see capture example at https://github.com/treydock/ssh_exporter#configuration, this example: 

```
    output_metric: true
    output_truncate: 50
```

https://github.com/treydock/ssh_exporter/blob/9c8412ffd904f1f9210d50dad3b3bfdd35dd258a/README.md?plain=1#L53-L54

I do not have any dashboards that use metrics from this exporter, I only use this exporter with alerts.

Based on your use case you might want to think about using node_exporter text file collector: https://github.com/prometheus/node_exporter#textfile-collector .  I have cron scripts write metrics to the directory node_exporter is looking at to get those metrics into Prometheus.  I can provide examples if that'd help.

**Comment by KeerthigaKrishnan** [comment]
Yes node exporter text file would help if you share the same .

**Comment by treydock** [comment]
Here's a cron script we use to detect if a filesystem is still accessible

```bash
#!/bin/bash

PROM="$1"
if [ "x$PROM" = "x" ]; then
    echo "Must specify path to .prom file"
    exit 1
fi
shift
FILES=( "$@" )
if [ ${#FILES[@]} -eq 0 ]; then
    echo "Must specify files to test"
    exit 1
fi

echo -n "" > $PROM.$$

ERR=0
TIME=$(date +%s)
TMP=$(mktemp /tmp/prometheus-file-test.XXXXXX)

  cat >> $PROM.$$ <<EOF
# HELP node_file_test_failure Indicates if file test has a failure
# TYPE node_file_test_failure gauge
EOF
for file in "${FILES[@]}"; do
  REASON=""
  VALUE=0
  ( OUTPUT=$(timeout -s KILL 5 cat ${file} 2>&1) ; echo "${file} ${OUTPUT} $?" >> $TMP ) & pid=$!
  ( sleep 10 && kill -9 $pid ) 2>/dev/null & watcher=$!

  if wait $pid 2>/dev/null; then
    if grep $file $TMP 2>&1 | grep -q " 124" >>/dev/null; then
      REASON="timeout"
    elif grep $file $TMP 2>&1 | grep -q " 137" >>/dev/null; then
      REASON="timeout"
    elif ! grep $file $TMP 2>&1 | grep -q " 0" >>/dev/null; then
      REASON="error"
    elif ! grep -q "${file} test" $TMP >>/dev/null; then
      REASON="invalid-output"
    fi
  else
    REASON="timeout"
  fi
  if [ -n "$REASON" ]; then
      VALUE=1
      echo "exporter=\"file-test\" level=error file=\"${file}\" reason=${REASON} output=\"$(grep $file $TMP)\""
  fi
  cat >> $PROM.$$ <<EOF
node_file_test_failure{file="${file}",reason="${REASON}"} $VALUE
EOF
done

cat >> $PROM.$$ <<EOF
# HELP cron_collector_time Time collected metrics
# TYPE cron_collector_time gauge
cron_collector_time{collector="file-test"} $TIME
# HELP cron_collector_error Error collecting metrics
# TYPE cron_collector_error gauge
cron_collector_error{collector="file-test"} $ERR
EOF

/bin/rm -f $TMP
/bin/mv -f $PROM.$$ $PROM
```

The cron entry looks like this:

```
*/10 * * * * /opt/osc/sbin/prometheus-file-test /var/lib/node_exporter/textfile_collector/autofs-file-test.prom /users/reporting/.testfile 2>&1 | logger -t cron_exporter
```

The cron job runs as `prometheus` user so `/var/lib/node_exporter/textfile_collector` must be writable by that user or the file written to pre-created with correct permissions. 

This is Python example we run to check output for InfiniBand command. Some of the modules we use aren't available to the public so just have to ignore them.

```python
#!/usr/bin/python

import argparse
from getpass import getuser
import filelock
import os
import subprocess
import sys
import logging
import re
import time
import traceback

from osc.logs import setup_logging
from osc.stdlib import exec_cmd

from prometheus_client import CollectorRegistry, Gauge, write_to_textfile

logger = logging.getLogger()

def collect(args):
    sminfo = {}
    cmd = ['/usr/sbin/sminfo']
    out, err, code = exec_cmd(cmd, sudo=True, runas='root')
    if code != 0:
        logger.error("Error executing sminfo, out=%s err=%s", out, err)
        return None
    regex = re.compile(r'.* sm lid ([0-9]+).*sm guid ([0-9a-z]+).*')
    m = regex.match(out)
    if m:
        sminfo['lid'] = m.group(1)
        sminfo['guid'] = m.group(2)
    else:
        logger.error("Cannot match %s", out)
        return None
    return sminfo

def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-d', '--debug', dest='debug', action='store_true')
    parser.add_argument('-f', '--full', action='store_true', default=False)
    parser.add_argument('-p', '--path', default=None)
    args, unknown_args = parser.parse_known_args()

    setup_logging(logger=logger, debug=args.debug)

    if not args.full and args.path is None:
        logger.error("Must specify --path or --full")
        sys.exit(1)

    registry = CollectorRegistry()
    time = Gauge('cron_collector_time', 'Time collected metrics', ['collector'], registry=registry)
    error = Gauge('cron_collector_error', 'Error collecting metrics', ['collector'], registry=registry)
    sminfo_metric = Gauge('sminfo_info', 'sminfo information', ['lid','guid'], registry=registry)
    try:
        flock = filelock.FileLock("/tmp/%s-sminfo.lock" % getuser(), 10)
        flock.acquire()
        sminfo = collect(args=args)
        if sminfo:
            sminfo_metric.labels(sminfo['lid'], sminfo['guid']).set(1)
            error.labels('sminfo').set(0)
        else:
            error.labels('sminfo').set(1)
    except filelock.Timeout:
        error.labels('sminfo').set(1)
        logger.error("Failed to acquire lock")
    except Exception as e:
        error.labels('sminfo').set(1)
        logger.error("ERROR: %s", str(e))
        logger.error("ERROR: %s", traceback.format_exc())

    time.labels('sminfo').set_to_current_time()
    if args.path is not None:
        write_to_textfile(args.path, registry)
    flock.release()

if __name__ == '__main__':
    main()
```
