### ISSUE TITLE
expect multiple groups of metrics

### ISSUE THREAD

**Issue by wgchaoer** [treydock/ssh_exporter#23]
How to collect when shell script outputs multiple metrics results? I don't want to use node_ exporter,SSH can remotely grab multiple groups of metrics

**Comment by treydock** [comment]
So this exporter is not intended to collect metrics via SSH. It's only meant to check that SSH is healthy from a remote system.  The ability to collect output is mostly just to verify you can SSH into a system and get login shell by running some command with known output.
